### ISSUE TITLE
App service not running

### ISSUE THREAD

**Issue by KaspianDev** [pterodactyl/development#12]
Hey, i installed dev env for ptero and just ran 
`./beak up -d`

But when i want to
`./beak app `
i get this error
`service "app" is not running container #1`

**Comment by KaspianDev** [comment]
Here's how i fixed it

Rename example .env file to .env, add WWWUSER=1000 line

**Comment by alexevladgabriel** [comment]
Hey @KaspianDev be sure to not run this command as root, it happened to me. That's the mistake most of us do.
